[package]
name = "campfire-backend"
version = "0.1.4"
edition = "2024"
authors = ["Braedon Smith <braedon.smith@kswg.cap.gov>"]
publish = false

[workspace]
members = [".", "api", "entity", "migration"]

[dependencies]
campfire-api = { path = "./api" }
