[package]
edition = "2024"
name = "entity"
publish = false
version = "0.1.6"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
serde = { version = "*", features = ["derive"] }

[dependencies.sea-orm]
version = "2.0.0-rc.30"